### ISSUE TITLE
feat: develop home ui

### ISSUE THREAD

**Issue by paiakarit** [cybermm/vpn-akms#15]
- The process will be developed and presented

## The Design System
- [x] creating a laptop design
- [x] creating a mobile design

> Note that the spacing used in the design is based on Tailwind CSS

**Comment by amm834** [comment]
Image assets တွေကောဘယ်မှာလဲဘရို

**Comment by paiakarit** [comment]
> Image assets တွေကောဘယ်မှာလဲဘရို

cover and logo က [art](https://github.com/cybermm/art) မှာရှိမယ် တစ်ခြားဟာတွေက [iconscount](https://iconscout.com) မှာရှိမယ်။

**Comment by amm834** [comment]
အိုကေဘရို

**Comment by paiakarit** [comment]
tablet design has been removed.
