### ISSUE TITLE
feat: create auth api

### ISSUE THREAD

**Issue by paiakarit** [cybermm/vpn-akms#23]

**Comment by kylesinlynn** [comment]
**ခဏနေပါဦးဟဲ့ 🥴**
ဒီဘက်မှာမီတင်တွေရောက်နေလို့ 🥺

**Comment by paiakarit** [comment]
> **ခဏနေပါဦးဟဲ့ woozy_face** ဒီဘက်မှာမီတင်တွေရောက်နေလို့ pleading_face

Ok Bo Gyi

**Comment by kylesinlynn** [comment]
Done ✔️

**Comment by paiakarit** [comment]
I'll reopen it to link in PR.

**Comment by paiakarit** [comment]
The issue has been linked with PR.
